# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f114b96bc9ba5ba839dc27e6cc315026cc7bd478d8bbaeb6541e64d9e42f72e87b7dff3ebee0bfc7811e127839b2f4537a9b0086a4aac9429a1bdc9f930b735f

test:
  secret_key_base: 15f433c964997342a746e8b1dcf7ca03e912b444d1608369efe1b903f8f8977cc9ed6d92701e1e3e544083826c6ca6f5a300af7ae2ff04e1cc009e8b7fc909f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
